app/urls.py
from django.conf.urls import url

from app.views import HomeView, ExportView, DownloadView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^export/', ExportView.as_view(), name='export'),
    url(r'^download/$', DownloadView.as_view(), name='download'),

]

spliter/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app.urls', namespace='app')),
    url(r'^admin/', admin.site.urls),
]

app/templates/ajax/list_files.html
{%load static%}
<style>
    .file{
    width: 100%;
    }

    .list_file h4 {
    width:100%;
    float:left;
    }
    .list_file h5 {
    width:100%;
    float:left;
    }

    .export {
    width: 100%;
    float:left;
    margin: 10px 0 0;
    }
     .column {
    float: left;
    width: 100px;
    margin: 0 10px 0 0;
    }
    .column input[type="text"] {
    width: 100%;
    }

    .rows{
    float: left;
    width: 100px;
    }
    .addBtn{
    float: left;
    width: 50px;
    margin: 18px 0 0;
    margin-left: 72px;
    }
    .clone{

    min-height:50px;
     display: block;
    }


</style>
<div class="list_file">
<form role="form" name="myform" method="post" novalidate id="upload" action="{% url 'app:export'%}">

    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token_value}}">
    <input type="hidden" name="type" value="export">


    <div class="lis_file">
        {% for list in tags %}
        <input type="hidden" class="tags" name="tags" value="{{ list.id }}">
            <div class="file">
                <h4>{{list.filename}}</h4>

                <h5><u>Positions</u></h5>
                <input type="hidden"  name="ids[]" id="selectedID" value="{{list.id}}">
                <div class="cloneDiv{{list.id}}">
                    <div class="inner{{list.id}}">
                        <div class="column">
                            <label>Column</label>
                            <input type="text" class="data-column" name="column{{list.id}}[]" class="" value="">
                        </div>
                        <div class="rows">
                            <label>Rows</label>

                            <input type="text" class="data-rows" name="rows{{list.id}}[]" class="" value="">
                        </div>
                    </div>

                </div>

                <button type="button" name="plus" value="{{list.id}}" class="addBtn">ADD</button>
            </div>
    </div>
    {%endfor%}
    <div class="export">
        <button type="button" name="export" id="sub-button">Export</button>
    </div>
    <div class="download">

    </div>
</form>
    </div>

<script>
$(document).ready(function(){
    $(".addBtn").click(function() {
        var value = $(this).val();
        console.log(value);
        console.log('************');
        var clone = $(".inner" + value + ":last").clone().appendTo('.cloneDiv' + value);
    });
});

$(document).ready(function(){
    $("#sub-button").click(function() {
       $(".export").removeClass(".download");
        var file_details = [];
        $( ".tags" ).each(function( i ) {
            var new_data = [];
            var data = $(this).val();
            $( ".inner"+data ).each(function( i ) {
                new_data.push({'col':$(this).find('.data-column').val(),'row':$(this).find('.data-rows').val()})
            });
            file_details.push({'id':data,'data':new_data})

        });


        var other_data = $('#upload').serializeArray();
        other_data.push({ name: "file_details", value: JSON.stringify(file_details) });

        $.ajax({
            url: "{% url 'app:export' %}",
            type: "POST",
            data: other_data,
            success: function (data) {
                console.log("*********************************");
                <!--window.location.replace("file:///C:" +"/home/spericorn-1/Documents/work/alex/spliter/combine.csv");-->
                <!--$(".export").append('<a href="{% url 'app:download'%}" class="download">Your file is ready!!</a>');-->
                $(".download" ).html( '<a href="{% url 'app:download'%}" class="download">Your file is ready!!</a>');

            }
        });
    });
})

</script>