app/urls.py
from django.conf.urls import url

from app.views import HomeView, ExportView, DownloadView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^export/', ExportView.as_view(), name='export'),
    url(r'^download/$', DownloadView.as_view(), name='download'),

]

spliter/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app.urls', namespace='app')),
    url(r'^admin/', admin.site.urls),
]

app/templates/file_edit.html
<div><h3>Export Data_Rows</h3></div>
<div>
    <label class="filename">File :</label>
<select class="mulselect" multiple>
    {% for file in files %}
  <option id="{{file.id}}" value="{{file.filename}}">{{file.filename}}</option>
 {% endfor %}
</select>
<h4>columns tobe combined</h4>
    <div class="list_file">

    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
<script>
$(document).ready(function(){
    $(".mulselect").change(function(){
        var ids = $(this).val();
        $.ajax({
           url:'{% url 'app:export' %}',
           type:'POST',
           data:{method_type: "get_files",ids: ids,'csrfmiddlewaretoken':'{{csrf_token}}'},
           success:function(data){
            if (data.status==true){
                $(".list_file").empty();
                $(".list_file").html(data.demo_data);
            }
            }
       });
    });
});

</script>

app/templates/file_upload.html
<style>
    .combine{
        -webkit-border-radius: 30px;
        -moz-border-radius: 30px;
        border-radius: 30px;
        background: green;
        padding: 5px;
        display: inline-block;
    }
</style>
<form method="post" action="{% url 'app:home' %}" enctype="multipart/form-data">
    {% csrf_token %}
{{ form.files }}
<h2>exclude header :- {{ form.exclude }}</h2>
<input type="submit" value="Import" />
</form>
{% for file in files %}

<!--<h3>{{file.rows}}</h3>-->
<!--<h3>{{file.files.columns.all}}</h3>-->
<div>
    <table>
        <tr>

            <td><h4>{{ file.files.filename }}</h4></td>

        </tr>
        <!--<tr>    <td><h5>Header</h5></td>-->
                    <!--{% for columns in file.columns %}-->
                        <!--<td>{{columns.column_header}}</td>-->

                    <!--{% endfor %}-->
            <!--</tr>-->

            <tr>
                <td><h5>Data_type</h5></td>
                {% for columns in file.columns %}
                <td id="type_{{columns.id}}">{{columns.types}}</td>
                {% endfor %}
            </tr>

            <tr>
                <form action="" method="post" role="form">
                    <td><h5>Change data_type</h5></td>
                {% for columns in file.columns %}
                <td ALIGN="center">
                   <select id="{{ columns.id}}" class="selectBox">

                        <option value="integer">integer</option>
                        <option value="float field">float field</option>
                        <option value="datefield">datefield</option>
                        <option value="string">string</option>
                   </select>
                </td>
                 {% endfor %}
                </form>
            </tr>


        {% for columns in file.rows %}


            <tr>
                <td><h5>File_content{{forloop.counter}}</h5></td>
                {% for tt in columns %}
                <td>{{tt.value}}</td>
                {% endfor %}
            </tr>

        {% endfor %}


    </table>

</div>
<p>--------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
{% endfor %}
<a href="{% url 'app:export'%}" class="combine">Export</a>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
<script>
$(document).ready(function(){
    <!--window.location.href  = "/home/spericorn-1/Documents/work/alex/spliter/combine.csv"-->
    <!--console.log("/home/spericorn-1/Documents/work/alex/spliter/combine.csv")-->
    $(".selectBox").change(function(){
        var id = $(this).val();
        var selectid = $(this).attr("id");
        console.log(id);
        console.log(selectid);
        $.ajax({
           url:'{% url 'app:home' %}',
           type:'POST',
           data:{method_type: "get-type",id: id,selectid: selectid,'csrfmiddlewaretoken':'{{csrf_token}}'},
           success:function(data){
            console.log(data);
            if (data.status==true)
            {

                console.log(data.re-id);
                var val = data.re-id;
                console.log(id);
                $('#type_'+selectid).html(id);

            }
            }
       });
    });
});

</script>